#!/bin/bash

set -eu

if [ $# -lt 3 ]; then
  echo "Usage: $0 <image name> <mount point> <EFI>"
  exit 1
fi

DISK_NAME=$1
MNT_POINT=$2
EFI=$3

rm -f "$DISK_NAME"
qemu-img create -f raw "$DISK_NAME" 200M
mkfs.fat -n 'ZAKURO OS' -s 2 -f2 -R 32 -F 32 "$DISK_NAME"

mkdir -p "$MNT_POINT"
sudo mount -o loop "$DISK_NAME" "$MNT_POINT"
sudo mkdir -p "$MNT_POINT/EFI/BOOT"
sudo cp "$EFI" "$MNT_POINT/EFI/BOOT/BOOTX64.EFI"

sleep 0.5
sudo umount "$MNT_POINT"
